-- !Ups
CREATE TABLE "USERS" (
  "ID" UUID PRIMARY KEY,
  "DATE_REGISTERED" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "USERNAME" VARCHAR(15) UNIQUE NOT NULL,
  "EMAIL" VARCHAR(50) UNIQUE NOT NULL,
  "PASSWORD" VARCHAR(255) NOT NULL,
  "FIRST_NAME" VARCHAR(50) NOT NULL,
  "MIDDLE_NAME" VARCHAR(50),
  "LAST_NAME" VARCHAR(50) NOT NULL,
  "GENDER" CHAR(1) NOT NULL,
  "BIRTH_DATE" DATE NOT NULL
);

CREATE TABLE "EMAILS" (
  "ID_EMAIL" UUID,
  "ID_USER" UUID,
  "EMAIL_USER" VARCHAR(50),
  "RECEPIENT" VARCHAR(50) NOT NULL,
  "ID_THREAD" UUID,
  "TITLE" VARCHAR(50) NOT NULL,
  "CONTENT" TEXT NOT NULL,
  "DATE_CREATED" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("ID_USER") REFERENCES "USERS" ("ID"),
  FOREIGN KEY ("EMAIL_USER") REFERENCES "USERS" ("EMAIL"),
  PRIMARY KEY ("ID_EMAIL", "EMAIL_USER", "ID_USER")
);

-- !Downs

DROP TABLE "EMAILS";
DROP TABLE "USERS";
